### ISSUE TITLE
Update Neo4j Go driver to latest 4.x

### ISSUE THREAD

**Issue by fbiville** [tlarsendataguy/graphyx#14]
Hello, I am the maintainer of the official Go driver for Neo4j.
I was wondering if the Go driver could be updated to the latest 4.x (currently 4.4.2).
I had a quick stab at it, but the compilation fails for unrelated reasons.

I remain available to discuss any potential blockers for this update.

**Comment by tlarsendataguy** [comment]
Thanks for submitting this issue! It looks like an easy update; all of the tests are green. It will take me a day or two to publish a new installer.

**Comment by fbiville** [comment]
Great news, thanks!

**Comment by tlarsendataguy** [comment]
Alright, a few more days than 1 or 2, but the installer is updated now with the latest Neo4j Go driver.
